# Generated by Django 3.0.5 on 2020-04-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
