# Generated by Django 3.0.5 on 2020-04-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0003_auto_20200420_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='category-2', upload_to='images'),
        ),
    ]
