# Generated by Django 3.0.5 on 2020-04-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0004_auto_20200420_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='image/images'),
        ),
    ]
