# Generated by Django 3.0.5 on 2020-04-21 01:20

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0006_product_afterdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='afterdiscount',
            field=computed_property.fields.ComputedFloatField(compute_from='calculation1', default=0, editable=False),
        ),
    ]
