# Generated by Django 3.0.5 on 2020-04-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0007_auto_20200420_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Featured_Product',
        ),
    ]
