# Generated by Django 3.0.5 on 2020-04-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0008_auto_20200420_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_product',
            name='description',
        ),
        migrations.AddField(
            model_name='featured_product',
            name='label',
            field=models.CharField(choices=[('FF', 'Farm Fresh'), ('OR', 'Organic'), ('Ex', 'Extract')], default=36, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('J', 'Juices'), ('V', 'Veggies'), ('D', 'Dried')], max_length=1),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamvegan.Featured_Product')),
            ],
        ),
    ]
