# Generated by Django 3.0.5 on 2020-04-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0009_auto_20200421_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_product',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('J', 'Juices'), ('V', 'Veggies'), ('D', 'Dried')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='label',
            field=models.CharField(choices=[('Farm Fresh', 'Farm Fresh'), ('OR', 'Organic'), ('Ex', 'Extract')], max_length=10),
        ),
    ]
