# Generated by Django 3.0.5 on 2020-04-21 04:55

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0010_auto_20200421_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Juices', 'Juices'), ('Veggies', 'Veggies'), ('Dried', 'Dried')], max_length=7)),
                ('label', models.CharField(choices=[('Farm Fresh', 'Farm Fresh'), ('Organic', 'Organic'), ('Extract', 'Extract')], max_length=10)),
                ('image', models.ImageField(upload_to='image/images')),
                ('quantity', models.IntegerField(default=1)),
                ('afterdiscount', computed_property.fields.ComputedFloatField(compute_from='calculation1', default=0, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Juices', 'Juices'), ('Veggies', 'Veggies'), ('Dried', 'Dried')], max_length=7),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='label',
            field=models.CharField(choices=[('Farm Fresh', 'Farm Fresh'), ('Organic', 'Organic'), ('Extract', 'Extract')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
