# Generated by Django 3.0.5 on 2020-04-21 05:00

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0011_auto_20200421_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_product',
            name='totalprice',
            field=computed_property.fields.ComputedFloatField(compute_from='calculation2', default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='totalprice',
            field=computed_property.fields.ComputedFloatField(compute_from='calculation2', default=0, editable=False),
        ),
    ]
