# Generated by Django 3.0.5 on 2020-04-21 05:55

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0012_auto_20200421_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billingdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('streetaddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('taxes', models.FloatField()),
                ('totalprice', computed_property.fields.ComputedFloatField(compute_from='calculation2', default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('orderdate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='featured_product',
            name='taxes',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.FloatField(default=13),
            preserve_default=False,
        ),
    ]
