# Generated by Django 3.0.5 on 2020-04-21 06:05

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0014_auto_20200421_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='afterdiscount',
            field=computed_property.fields.ComputedFloatField(compute_from='calculation1', default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='phonenumber',
            field=models.IntegerField(max_length=12),
        ),
    ]
