# Generated by Django 3.0.5 on 2020-04-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0016_auto_20200421_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_product',
            name='afterdiscount',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='label',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='featured_product',
            name='totalprice',
        ),
        migrations.AddField(
            model_name='featured_product',
            name='featured_product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='iamvegan.Product'),
            preserve_default=False,
        ),
    ]
