# Generated by Django 3.0.5 on 2020-04-22 02:33

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0021_auto_20200421_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_product',
            name='afterdiscount',
            field=computed_property.fields.ComputedFloatField(blank=True, compute_from='calculation1', editable=False),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruits', 'Fruits'), ('Juices', 'Juices'), ('Veggies', 'Veggies'), ('Dried', 'Dried')], max_length=7),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='discounted_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='label',
            field=models.CharField(blank=True, choices=[('Farm Fresh', 'Farm Fresh'), ('Organic', 'Organic'), ('Extract', 'Extract')], max_length=10),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='totalprice',
            field=computed_property.fields.ComputedFloatField(blank=True, compute_from='calculation2', editable=False),
        ),
    ]
