# Generated by Django 3.0.5 on 2020-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0022_auto_20200421_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundimages', models.ImageField(default='', upload_to='image/images')),
                ('aboutusimages', models.ImageField(default='', upload_to='image/images')),
                ('categoryimages', models.ImageField(default='', upload_to='image/images')),
                ('partnerimages', models.ImageField(default='', upload_to='image/images')),
            ],
        ),
    ]
