# Generated by Django 3.0.5 on 2020-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0023_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_image', models.CharField(choices=[('BACKGROUND_IMAGES', 'BACKGROUND_IMAGES'), ('ABOUT_US_IMAGES', 'ABOUT_US_IMAGES'), ('CATEGORY_IMAGES', 'CATEGORY_IMAGES'), ('PARTNER_IMAGES', 'PARTNER_IMAGES')], max_length=20)),
                ('images', models.ImageField(blank=True, upload_to='image/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
