# Generated by Django 3.0.5 on 2020-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0030_auto_20200423_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='pimages'),
        ),
    ]
