# Generated by Django 3.0.5 on 2020-04-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamvegan', '0037_auto_20200424_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_product',
            name='stock',
        ),
    ]
